import { Inter } from 'next/font/google';
import 'bootstrap/dist/css/bootstrap.min.css';
import NavBar from '@/components/nav/nav';
import TableComponent from '@/components/table/table';
import Container from 'react-bootstrap/Container';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <NavBar/>
        </div>
          {children}
        <div>
          <TableComponent/>        
        </div>
        <div style={{ background:'#ddd', textAlign: 'center', padding: '20px', marginTop: '20px' }}>
           Next.JS v13 Basic
        </div>
      </body>
    </html>
  )
}
